name : 'CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  BUCKET: vpc-ec2bucket
  TFSTATE_FILE: new.tfstate 
  DB_TABLE: vpc-ec2


jobs:
  terraform:
    name: Terraform
    runs-on:  ubuntu-latest

    

    defaults:
      run:
        working-directory: ./modules

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:      ${{ secrets.AWS_SESSION_TOKEN }} 

          aws-region: eu-central-1     

      - name: Terraform Init
        id: init
        run:
          terraform init -reconfigure
         -backend-config="bucket=$BUCKET" 
         -backend-config="key=$TFSTATE_FILE" 
         -backend-config="dynamodb_table=$DB_TABLE"
      
      
      - name: Terraform validate
        id: validate 
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run:  terraform apply -auto-approve